<?xml version="1.0" encoding="utf-8"?><Database Name="rumurciata" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=rumurciata.mssql.somee.com;Initial Catalog=rumurciata;User ID=rumurciata_SQLLogin_1" SettingsObjectName="GuardaPass.Properties.Settings" SettingsPropertyName="rumurciataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TBL_GUARDA_PASS" Member="TBL_GUARDA_PASS">
    <Type Name="TBL_GUARDA_PASS">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USUARIO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PASS" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPCION" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>